# TAXA : ['5', '10', '25', '50']


TAXA : ['6', '12', '20', '25', '40']

REPS : 5

GRASP_METHODS : ['SICML', 'BEP', 'SICP', 'PSP', 'BEML', 'PSML']


# Problems - 'BEML'

#'BEML', 'PSP'
# GRASP_METHODS : ['BEP' ]

# GRASP_METHODS : ['PSML']

# GRASP_METHODS : ['BEP']
