# TAXA : ['5', '10', '25', '50']


TAXA : ['5']

REPS : 1

GRASP_METHODS : ['SICML', 'BEP', 'SICP', 'PSP', 'BEML', 'PSML']


# GRASP_METHODS : ['SICML', 'BEP', 'SICP', 'PSP', 'BEML', 'PSML']

# Problems - 'BEML'

#'BEML', 'PSP'
# GRASP_METHODS : ['BEP' ]

# GRASP_METHODS : ['PSML']

# GRASP_METHODS : ['BEP']
