>N0
A-SDIE-W-GA---TT--DHVMSTCEGE
>sequence2
Q-SFFE-A-QG---SS----ATPTYEGS
>N1
A-SDIE-W-GA---TT--DHVMSTCEGE
>sequence3
A------------------SVHSTVEGE
>N2
D-SDIE-W-GA---TT--DHVM-KCEGE
>sequence4
A-Q----WeGEyraTVsk----------
>sequence1
D-SDIEfW-GA---TT--DHVM-KCEGE
>sequence5
VhSEID-W-GA---TT--SYVM-KCETV
